### ISSUE TITLE
Correct Answer Should Not Be Revealed After Incorrect Response

### ISSUE THREAD

**Issue by ajkofman** [tylerharter/cs301-projects#72]
test.py says "You answered 'a'. The correct answer is 'c'." after any answer. Per the instructions, this should only be displayed after no tries remain.

It is unclear whether this message should be displayed after a correct answer is given.

**Comment by ajkofman** [comment]
test.py does not reveal correct answer after correct response.

**Comment by tylerharter** [comment]
Thanks for posting these!  Email (cs301-ta@lists.wisc.edu) is usually a better channel for letting us know about issues, though (we won't be watching github issues closely).
